### ISSUE TITLE
Fails when used with httpApi gateway

### ISSUE THREAD

**Issue by MarcoPolo** [awslabs/aws-lambda-rust-runtime#212]
When using a lambda with [HTTP API Gateways](https://aws.amazon.com/blogs/compute/announcing-http-apis-for-amazon-api-gateway/) it fails to parse the incoming event. I think it's because http apis don't pass a resource id, so the deserializing fails. Maybe something like this would fix it: https://github.com/MarcoPolo/aws-lambda-rust-runtime/commit/b0091cb21fa38e9f96b91370ce711dd29854c980?

You can repro by using something like the following in a serverless.yml config:
```
...
functions:
  fooFn:
    handler: fooHandler
    events:
      - httpApi:
          path: /
          method: GET
```
