### ISSUE TITLE
`lambda_attributes` is a non-optional dependency for `lambda`

### ISSUE THREAD

**Issue by stanislav-tkach** [awslabs/aws-lambda-rust-runtime#264]
According to the `lambda` `Cargo.toml` [file](https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/lambda/Cargo.toml#L22), `lambda-attributes` is an optional dependency:
```toml
[features]
default = ["simulated", "derive"]
derive = ["lambda-attributes"]

[dependencies]
lambda-attributes = { path = "../lambda-attributes", version = "0.1.0", optional = true}
```
But in the `lambda/lib.rs` [file](https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/lambda/Cargo.toml#L22) `lambda-attributes` is used unconditionally:
```rust
pub use lambda_attributes::lambda;
```
Therefore it is impossible to use `lambda` with `default-features = false`.
