### ISSUE TITLE
When running "cargo lambda watch" in examples/http-axum, consistent "internal error watching your project..."

### ISSUE THREAD

**Issue by waltojac** [awslabs/aws-lambda-rust-runtime#600]
I have cloned tried to run [the http-axum example](https://github.com/awslabs/aws-lambda-rust-runtime/tree/main/examples/http-axum) locally using ``` cargo lambda watch  -p 9001 ```. It does successfully respond to requests, but while it is just sitting, it throws an error and re-compiles every second or so.

```
ERROR internal error watching your project error=IoError { about: "waiting on process group", err: Os { code: 10, kind: Uncategorized, message: "No child processes" } }
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/http-basic-lambda`
ERROR internal error watching your project error=IoError { about: "waiting on process group", err: Os { code: 10, kind: Uncategorized, message: "No child processes" } }
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/http-basic-lambda`
```

I initially tried running the example from within this parent project, and then pulled it out into its own directory, updating the `lambda-runtime` and `lambda-http` dependencies to "0.7.3" and the same error occurs. 

I am running this on an M1 Mac. Originally, I had rustc 1.65.0 (897e37553 2022-11-02), but ran `rustup update` to the latest (rustc 1.67.1 (d5a82bbd2 2023-02-07)) with the same results.

Again, it does still respond successfully to requests over `http://localhost:9001/lambda-url/http-basic-lambda`, it just keeps recompiling every second or so.

**Comment by winstxnhdw** [comment]
Since I am stuck on my issue and the maintainers are taking a break. Let me try to troubleshoot your issue. Unfortunately, I am not able to reproduce your issue. The server successfully responds to requests and it never recompiles every second or so like you mentioned. I am on rustc 1.67.1 but I am on a Arch Linux x86 machine, so that could be why. Fwiw, this might just be a `cargo-lambda` issue and not a lambda-runtime one. You should test this on the actual Lambda and see if your problem still occurs.

Here's my `Cargo.toml` according to the `http-axum` example.

```toml
[package]
name = "http-basic-lambda"
version = "0.1.0"
edition = "2021"


# Use cargo-edit(https://github.com/killercup/cargo-edit#installation)
# to manage dependencies.
# Running `cargo add DEPENDENCY_NAME` will
# add the latest version of a dependency to the list,
# and it will keep the alphabetic ordering for you.

[dependencies]
lambda_http = { version = "^0.7.3" }
lambda_runtime = { version = "^0.7.3" }

tokio = { version = "1", features = ["macros"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }

axum = "0.6.4"
serde_json = "1.0"
```
