### ISSUE TITLE
Invoking HTTP API with cargo lambda watch locally does not return anything?

### ISSUE THREAD

**Issue by DataPsycho** [awslabs/aws-lambda-rust-runtime#617]
Hi,
I was trying out the `cargo lambda` to build a http api. So I used the default cli to generate the code for me and added my own code into the main file. Here is the main file looks like:

```rust
use lambda_http::{run, service_fn, Body, Error, Request, Response};
use serde;
use tracing::info;

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct Item {
    pub username: String,
    pub age: String,
}


async fn function_handler(event: Request) -> Result<Response<Body>, Error> {
    // Extract some useful information from the request
    let body = event.body();
    let s = std::str::from_utf8(body).expect("invalid utf-8 sequence");
    info!(payload = %s, "JSON Payload received");

    let item = match serde_json::from_str::<Item>(s) {
        Ok(item) => item,
        Err(err) => {
            let resp = Response::builder()
                .status(400)
                .header("content-type", "text/html")
                .body(err.to_string().into())
                .map_err(Box::new)?;
            return Ok(resp);
        }
    };

    let j = serde_json::to_string(&item)?;

    info!("{}", j);

    // Return something that implements IntoResponse.
    // It will be serialized to the right response event automatically by the runtime
    let resp = Response::builder()
        .status(200)
        .header("content-type", "text/html")
        .body(j.into())
        .map_err(Box::new)?;
    Ok(resp)
}

#[tokio::main]
async fn main() -> Result<(), Error> {
    tracing_subscriber::fmt()
        .with_max_level(tracing::Level::INFO)
        // disable printing the name of the module in every log line.
        // .with_target(false)
        // disabling time is handy because CloudWatch will add the ingestion time.
        // .without_time()
        .init();

    run(service_fn(function_handler)).await
}
```
Now I run `cargo lambda watch -v` to start the server which shows following output:
```
INFO invoke server listening on [::]:9000
``` 

The I use curl to invoke the lambda endpoint:
```
curl -X POST http://localhost:9000/lambda-url/test-lambda-http -H "Content-Type: text/html" -d '{"username": "abc", "age": "100"}'  -v
```

Which returns:
```
*   Trying 127.0.0.1:9000...
* Connected to localhost (127.0.0.1) port 9000 (#0)
> GET /lambda-url/test-lambda-http HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Type: application/json
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 308 Permanent Redirect
< location: /lambda-url/test-lambda-http/
< content-length: 0
< date: Sun, 12 Mar 2023 17:12:50 GMT
< 
* Connection #0 to host localhost left intact
```
But with no response. It is connecting the end point but not returning any response. Also I do not see any error on the server runtime console. No tracing or log.

Here is the cargo toml file:

```toml
[package]
name = "test-lambda-http"
version = "0.1.0"
edition = "2021"

# Starting in Rust 1.62 you can use `cargo add` to add dependencies 
# to your project.
#
# If you're using an older Rust version,
# download cargo-edit(https://github.com/killercup/cargo-edit#installation) 
# to install the `add` subcommand.
#
# Running `cargo add DEPENDENCY_NAME` will
# add the latest version of a dependency to the list,
# and it will keep the alphabetic ordering for you.

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
lambda_http = { version = "0.7", default-features = false, features = ["apigw_http"] }
lambda_runtime = "0.7"
tokio = { version = "1", features = ["macros"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }
```
