### ISSUE TITLE
How to do a debug build?

### ISSUE THREAD

**Issue by jifalops** [awslabs/aws-lambda-rust-runtime#671]
When using `BuildMethod: rust-cargolambda` in my `template.yaml`, I cannot seem to get `sam build` or `sam local start-api` to omit the `--release` flag passed to `cargo lambda build`.

I've tried this, but it doesn't seem to do anything, although valid (`sam validate`):

```yml
Parameters:
  BuildCommand:
    Type: String
MyFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildCommand: !Ref BuildCommand
```

```sh
# Ignores BuildCommand
sam build --debug --parameter-overrides BuildCommand="/usr/local/cargo/bin/cargo lambda build"
# Ignores, should it even be passed here?
sam local start-api --debug --parameter-overrides BuildCommand="/usr/local/cargo/bin/cargo lambda build"
```

I've looked through the articles on AWS, issues on this repo, and various searching, but there have been no mentions of doing debug builds through SAM that I can find.
