### ISSUE TITLE
Error: /lib64/libc.so.6: version `GLIBC_2.28' not found

### ISSUE THREAD

**Issue by baolongt** [awslabs/aws-lambda-rust-runtime#878]
I'm facing this error when I try to use this command 

`cargo lambda build --release --target x86_64-unknown-linux-gnu`

my `template.yml`

```
Globals:
  Function:
    MemorySize: 128
    Architectures: ["x86_64"]
    Handler: bootstrap
    Runtime: provided.al2
    Timeout: 30
    Tracing: Active
    Environment:
      Variables:
        RUST_LOG: info
```

It work with `x86_64-unknown-linux-musl`. But from this [issue ](https://github.com/awslabs/aws-lambda-rust-runtime/discussions/306) it said I should use gnu instead of musl
