### ISSUE TITLE
JsonError: missing field `path`

### ISSUE THREAD

**Issue by ffissore** [awslabs/aws-lambda-rust-runtime#95]
When I deploy the lambda-http basic example and call it via api gateway, I get
```json
{
  "errorMessage": "JsonError: missing field `path` at line 1 column 2",
  "errorType": "JsonError",
  "stackTrace": null
}
```

It seems like having a `Request` in the handler function is not supported.

How can I make a lambda which handles both GET and POST invocations via api gateway?

**Comment by softprops** [comment]
For your first question, how are you currently deploying your lambda and to what region?

To answer your second question. There's an example of a GET request in this [serverless framwork template](https://github.com/softprops/serverless-aws-rust-http/blob/master/serverless.yml#L53-L57) You can extend this example's configuration to subscribe to POST requests with the following

```yaml
    handler: hello
    events:
      - http:
          path: '/'
          method: GET
      - http:
          path: '/'
          method: POST
```
