### ISSUE TITLE
Possible memory leak? After cold start, lambda keeps consuming memory

### ISSUE THREAD

**Issue by nicoan** [awslabs/aws-lambda-rust-runtime#972]
Hello,

Working on some lambdas I noticed that the memory consumption keeps incrementing and never goes down. I made several tests all of them threw more or less the same results. Here's the code I used for testing:

```rust
use lambda_http::{service_fn, Error, Request};

pub async fn function_handler(_: Request) -> Result<&'static str, Error> {
    Ok("")
}

#[tokio::main]
async fn main() -> Result<(), Error> {
    lambda_http::run(service_fn(function_handler)).await
}
```

Cargo.toml
```toml
[package]
name = "test_leak"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "0.14.0"
tokio = { version = "1", features = ["macros"] }
```

To run the tests, I used an script that calls an API Gateway endpoint that calls the lambda:

```bash
#!/bin/bash
for ((i=1; i<=5000; i++)); do
    curl -i -X POST <api_g_url> -H 'Content-Type: application/json' --header 'Content-Length: 6' -d '"test"'
done
```

Here are the graphs of the memory consumption from the tests:

![Image](https://github.com/user-attachments/assets/ad742b67-8774-4008-a392-e502656f5376)
![Image](https://github.com/user-attachments/assets/2ae736fb-6912-40c1-ba02-a864ede6b7ae)
![Image](https://github.com/user-attachments/assets/d49ece8f-2469-4537-8255-083b395f2dec)
![Image](https://github.com/user-attachments/assets/71d6220c-e518-42b0-bad5-7bde83c86fd5)
